baseurl = "/"
title = "MU 💻 blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    description = "🔑 === Documentation"
    headline = "Home"
    github = "https://github.com/mariourban83"
    linkedin = "https://www.linkedin.com/in/mariourban83/"
    email = "u.mario@seznam.cz"
    opengraph = true

[Permalinks]
    post = "/:filename/"
theme = "ghostwriter"
